// Generated by https://quicktype.io

class CastModel {
  String? knownForDepartment;
  String? name;
  String? profilePath;
  String? character;

  CastModel({
    this.knownForDepartment,
    this.name,
    this.profilePath,
    this.character,
  });

  factory CastModel.fromMap(Map<String, dynamic> map) {
    return CastModel(
      knownForDepartment: map['known_for_department'],
      name: map['name'],
      profilePath: map['profile_path'] ?? '',
      character: map['character'],
    );
  }
}
